#!/bin/sh

set -e

sudo apt-get -y update
sudo apt-get -y install automake g++ make gawk qemu xorriso

sudo -u vagrant /vagrant/script/build_cross_gcc /home/vagrant/build
sudo -u vagrant bash -c 'echo "export PATH=\"$HOME/build/opt/cross/bin:\$PATH\"" > ~/.bash_profile'
